dubbo:
  application:
    id: tp-dubbo-nacos
    name: tp-dubbo-nacos
  registry:
    id: tp-dubbo-nacos
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: org.thinkstop.service
demo:
  service:
    version: 1.0.5
    name: tp-demo
server:
  port: 9099
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
  application:
    name: dubbo-nacos-privode